//Update this data to see changes in the file

module.exports = {
 email: "example@advancedkiosks.com",
 organizationname: "Example Organization",
 reportingperiod: "07/30 - 08/05",
 kioskId: "1673969906805",
 kioskName: "Lobby Kiosk",
 location: "Concord",
 serialNumber: null,
 sessionweeklycount: 0,
 sessionaveragedurationmissing: true,
 sessioncounttrendingdelta: "-100%",
 sessionday1usage: 0,
 sessionday2usage: 0,
 sessionday3usage: 0,
 sessionday4usage: 0,
 sessionday5usage: 0,
 sessionday6usage: 0,
 sessionday7usage: 0,
 printweeklycount: 0,
 voipweeklycallcount: 0,
 voipaveragecalldurationmissing: true,
 satisfactionsadcount: 0,
 satisfactionneutralcount: 0,
 satisfactionhappycount: 0,
 satisfactionresponsecount: 0,
 landingpagebutton1clicksmissing: true,
 landingpagebutton1labelmissing: true,
 landingpagebutton2clicksmissing: true,
 landingpagebutton2labelmissing: true,
 landingpagebutton3clicksmissing: true,
 landingpagebutton3labelmissing: true,
 webfilterblockedcount: 0,
 notificationstotalcount: 0,
 notificationstotalcountmissing: "",
 notificationspopulartype1missing: true,
 notificationspopulartype2missing: true,
 notificationspopulartype3missing: true,
 subscriptionabouttoexpire: "",
 scanningweeklycount: 0,
 scanningaveragepagesmissing: true,
};
